# Site settings
title:       "Andrey Miskov"
header_title: "Разные заметки"
email:       amiskov@gmail.com
author:      Andrey Miskov
description: ""
baseurl:     ""
url:         "https://amiskov.github.io"
date_format: "%-d.%m.%Y"

# Google services
google_analytics: ""
google_verification: ""

# Facebook
facebook_app_id: ""

# Optional features
animated:             false
show_related_posts:   false
show_post_footer:    true
show_social_icons:    false
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "amiskov"

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
facebook_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:title/"
paginate:     15
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
